-- Índices opcionales para /api/v1/companies/filter (segmentos), 29-09-2026.
-- Antes de crear nada, mira qué hay y cuánto tarda un recuento típico:
--
--   SHOW INDEX FROM companies;
--   EXPLAIN SELECT COUNT(*) FROM companies
--     WHERE cnae_code LIKE '62%' AND registro_mercantil = 'MADRID' AND estado = 'ACTIVA';
--
-- Si el EXPLAIN recorre la tabla entera (type = ALL, rows ~ 4,7 millones) y el recuento tarda
-- más de 2-3 segundos, crea este índice. Tarda varios minutos en una tabla de este tamaño:
-- lánzalo en local primero y en producción fuera de horas.
--
-- CREATE INDEX idx_companies_prov_cnae_estado ON companies (registro_mercantil, cnae_code, estado);
--
-- Para búsquedas solo por CNAE (sin provincia), si no existe ya un índice que empiece por cnae_code:
--
-- CREATE INDEX idx_companies_cnae ON companies (cnae_code);
