CREATE TABLE IF NOT EXISTS `company_radar_scores` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `company_id` BIGINT UNSIGNED NOT NULL,
    `score_total` INT DEFAULT 0,
    `score_act_type` INT DEFAULT 0,
    `score_recency` INT DEFAULT 0,
    `score_capital` INT DEFAULT 0,
    `score_legal_form` INT DEFAULT 0,
    `score_activity` INT DEFAULT 0,
    `score_object` INT DEFAULT 0,
    `score_location` INT DEFAULT 0,
    `score_name` INT DEFAULT 0,
    `score_admin_signal` INT DEFAULT 0,
    `penalty_score` INT DEFAULT 0,
    `priority_level` ENUM('muy_alta', 'alta', 'media', 'baja', 'muy_baja') DEFAULT 'muy_baja',
    `score_reasons` TEXT,
    `main_act_type` VARCHAR(255),
    `last_borme_date` DATE,
    `last_post_id` BIGINT UNSIGNED,
    `calculation_version` VARCHAR(50) DEFAULT '1.0.0',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `unique_company` (`company_id`),
    INDEX `idx_score_total` (`score_total`),
    INDEX `idx_priority_level` (`priority_level`),
    INDEX `idx_last_borme_date` (`last_borme_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
